name: Build TDLib for Windows 64-bit

on:
  workflow_dispatch: # Allows you to run the workflow manually from the Actions tab

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Cache vcpkg dependencies
      uses: actions/cache@v4
      id: vcpkg-cache
      with:
        path: |
          td/vcpkg/installed
          td/vcpkg/packages
          td/vcpkg/downloads
        key: ${{ runner.os }}-vcpkg-bc3512a509f9d29b37346a7e7e929f9a26e66c7e
        restore-keys: |
          ${{ runner.os }}-vcpkg-

    - name: Build and Install TDLib
      shell: pwsh
      run: |
        git clone https://github.com/tdlib/td.git
        cd td
        
        # Force vcpkg to build static libraries to avoid linking issues
        $env:VCPKG_DEFAULT_TRIPLET="x64-windows-static"
        
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        git checkout bc3512a509f9d29b37346a7e7e929f9a26e66c7e
        ./bootstrap-vcpkg.bat
        ./vcpkg.exe install gperf openssl zlib
        cd ..
        
        Remove-Item build -Force -Recurse -ErrorAction SilentlyContinue
        mkdir build
        cd build
        
        # Pass the static triplet to CMake as well
        cmake -A x64 -DCMAKE_INSTALL_PREFIX:PATH=../tdlib -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static ..
        cmake --build . --target install --config Release
        cd ..
        cd ..
        dir td/tdlib

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tdlib-release-windows-x64
        path: td/tdlib/
        if-no-files-found: error

